summary = open(outdir + "summary.tsv", "w")
summary.write("Patient")
summary.write("\tSample")
summary.write("\tnPoints")
summary.write("\tCall")
summary.write("\tGroup")
summary.write("\tMean x2")
summary.write("\tStdev x2")
summary.write("\tHistMax x2")
summary.write("\tHistMax height")
summary.write("\tHistMax x2")
summary.write("\tHistMax height")
summary.write("\tHistMax x2")
summary.write("\tHistMax height")
summary.write("\tHistMax x2")
summary.write("\tHistMax height")
summary.write("\tHistMax x2")
summary.write("\tHistMax height")
summary.write("\tHistMax x2")
summary.write("\tHistMax height")
summary.write("\n")

